### ISSUE TITLE
i18n message file support

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticInterlanguageLinks#1]
After seeing issues with tn.w (https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/693) again, I'm not going through the trouble of creating a tn.w/gerrit entry. Changes to `SIL` messages should be made directly to this repo.

**Comment by jaideraf** [comment]
@kghbln, maybe this can help you a little:
https://translatewiki.net/w/i.php?title=Special:MessageGroupStats&group=ext-semanticmediawiki#sortable:3=desc

**Comment by kghbln** [comment]
Not really since this only tells us which languages are localised to a satisfactory extent and not how many instances actually run a specific language. My guess about languages was a bit based on what I see on the mailing list and what I meet on SWMCons. I may very well have omitted the one or other language. French, Italian and Portuguese are probably among them. We should also check WikiApiary for info on this to get a more solid picture.

Apart from this: Throw in you patch for Brazilian Portuguese :)

**Comment by jaideraf** [comment]
@kghbln Done :)
But, as I am not a developer, the last time I tried to contribute by GitHub it did not work very well:
https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/28
So, sorry, if I do something wrong here ;)
That's why translatewiki.net exists.

**Comment by mwjames** [comment]
> So, sorry, if I do something wrong here ;)

No worries, if something doesn't fit right away we are able to help. The important thing is the contribution. :+1:

**Comment by mwjames** [comment]
> That's why translatewiki.net exists.

The problem is that there is no merit in requesting WMF gerrit access (which takes some time and it is administrative exhausting) then constantly maintain and synchronize with the github instance (as done by SMW) due to translatewiki.net being only aware of WMF gerrit for updating translation and if for some reason you miss the sync you suddenly end-up having content removed (as in #693).

**Comment by JeroenDeDauw** [comment]
Is ditching TWN not a bit of an overreaction? Sure, they caused a problem once in the last year, though if you look at how few problems are caused for all the value added, is that really not worth it?

**Comment by mwjames** [comment]
> Is ditching TWN not a bit of an overreaction?

It is not worth my time.

**Comment by JeroenDeDauw** [comment]
> It is not worth my time.

That's entirely fair - if you don't want to spend your time on that, then you don't. Would you object if I request a WMF repo to be created and sync that every now and then like done for SMW and a bunch of other extensions?

**Comment by mwjames** [comment]
> Would you however object if I request a WMF repo to be created and sync that every now and then like done for SMW and a bunch of other extensions?

No objections, go ahead and knock yourself out.

**Comment by JeroenDeDauw** [comment]
> go ahead and knock yourself out.

@kghbln Now James has given us permission, I got a plan on how to proceed

![snow](https://cloud.githubusercontent.com/assets/146040/5867069/edf1538e-a297-11e4-9242-0f4bb0e5ce1b.gif)

**Comment by JeroenDeDauw** [comment]
Repos requested https://www.mediawiki.org/w/index.php?title=Git%2FNew_repositories%2FRequests%2FEntries&diff=1369510&oldid=1362854
