### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticInterlanguageLinks#24]
* Added an INTERLANGUAGELINK parser to easily create interlanguage related semantic annotations
* Added an INTERLANGUAGELIST parser to support template output for available interlanguage links
* Added a search profile to Special:Search to enable language filtering on the basis of avilable semantic annotations
* Added ByLanguageCategoryViewer to enable auto-filtering for pages within a catgory that declare a content language using the INTERLANGUAGELINK parser

@SemanticMediaWiki/testers I'd like to make the 1.0 release but would appreciate some testing before against the claimed features. If you are not sure what to test, have a look at the [video](https://vimeo.com/115871518) for more details. (You need SMW 2.1 and it is best to install it via Composer as it requires another library as dependency).

**Comment by JeroenDeDauw** [comment]
@mwjames want any help with the rel from my side?

**Comment by mwjames** [comment]
> want any help with the rel from my side?

Well, I expected some feedback but now that the last piece (to cover the interwiki topic with its natural `[[en:Foo]]` annotation to be handled by `InterwikiLanguageLinkFetcher`) has been merged I can't see a reason as to why not to do a release.

**Comment by JeroenDeDauw** [comment]
That actually does not really answer my question :)

**Comment by JeroenDeDauw** [comment]
@mwjames so, shall I create a tag and write a release email?

**Comment by mwjames** [comment]
>  so, shall I create a tag and write a release email?

Again, I would be much obliged.

**Comment by JeroenDeDauw** [comment]
1.0.0 tag created
