### ISSUE TITLE
`{{{lang-name}}}` should stick to the language name

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticInterlanguageLinks#45]
### Setup and configuration

- MediaWiki 	1.28.0-rc.0 (7625c75) 15:14, 3. Nov. 2016
- PHP 	5.6.27-0+deb8u1 (apache2handler)
- MariaDB 	10.0.28-MariaDB-1~jessie
- Semantic MediaWiki	2.5.0-alpha (4ca198b) 00:09, 6. Nov. 2016
- Semantic Interlanguage Links	1.3.0 (c10a0ad) 08:03, 3. Nov. 2016

### Issue

In case on changes the display title of a page with DISPLAYTITLE the `{{{lang-name}}}` variable to the `interlanguagelist` parser function picks up the display title rather than sticking to the page's language. See the page on [Mainz](http://sandbox.semantic-mediawiki.org/wiki/Mainz). There are probably cases where one would perhaps like to get the display title rather than the language name but if I really had to choose I would only like to the the language name. Have not checked the `{{{lang-code}}}` variable but this one is likely to be affected, too.

**Comment by mwjames** [comment]
> In case on changes the display title of a page with DISPLAYTITLE the {{{lang-name}}} variable to the interlanguagelist parser function picks up the display title

Some notes:

- The code [0] that produces `lang-name` relies on `Language::fetchLanguageName( $languageCode )` therefore you should not see/have any reference to the `DISPLAYTITLE`
- I tried to reproduce the case locally using the example from the sandbox but I was unable to make a similar observation 

Next steps:

- Please add `var_dump( $wikitext );` below the [0] line for a short test. After adding the line please purge the page expecting the top to output something like below.
- In the produced output we should not see any reference to `Mainz am Rhein`
- Once the template text has been composed anything that happens thereafter is done by the MediaWiki `Parser`
- This reminds of https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/15! Does `refreshLinks.php` bring any improvement? 

![image](https://cloud.githubusercontent.com/assets/1245473/20062834/73ddf59e-a505-11e6-9a1d-57768a48ebb4.png)

Template used:

```
<includeonly><span style="margin-right: 5px; background-color:#f3f3f3;">[[{{{target-link}}}|{{{lang-name}}}]]</span></includeonly>
```

[0] https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/blob/master/src/InterlanguageListParserFunction.php#L90

**Comment by kghbln** [comment]
> Please add var_dump( $wikitext ); below the [0] line for a short test

string(0) "" string(0) "" string(0) ""

> In the produced output we should not see any reference to Mainz am Rhein

Well it does not but since everything it empty ...

**Comment by kghbln** [comment]
"refreshLinks.php" also dumps `string(0)`

**Comment by mwjames** [comment]
This morning I moved some lines hence the said `var_dump` should be before `$templateText .= '{{' . $template . $wikitext . '}}';`.

**Comment by mwjames** [comment]
> since I was fiddling with this functionality

Somehow I suspect that it is either some customizing or another extension that juggles with the links.

**Comment by kghbln** [comment]
So here we are

```string(57) "|#=0|target-link=Magúncia|lang-code=ca|lang-name=català" string(53) "|#=1|target-link=Mainz|lang-code=de|lang-name=Deutsch" string(57) "|#=2|target-link=Mayence|lang-code=fr|lang-name=français"
```
> Somehow I suspect that it is either some customizing or another extension that juggles with the links.

Probably and extension then since sandbox does not really have a lot of customizing.

**Comment by kghbln** [comment]
> Probably and extension then since sandbox does not really have a lot of customizing.

There was one prime suspect. After commenting out 
```php
## Semantic Title
// require 'extensions/SemanticTitle/SemanticTitle.php';
// $wgSemanticTitleProperties = array(
//        NS_MAIN => 'Has pagetitle'
//        );
```
things were in fluff.

**Comment by mwjames** [comment]
`link=Mainz|lang-code=de|lang-name=Deutsch` is what we return as template content back to the parser which produces a link based on `[[{{{target-link}}}|{{{lang-name}}}]]`.

**Comment by mwjames** [comment]
> things were in fluff.

Nice catch. (Now that we found the culprit, you can remove the `var_dump` call.)

**Comment by kghbln** [comment]
Well @cicalese discouraged the usage of the [`$wgSemanticTitleProperties`](https://www.mediawiki.org/wiki/Topic:Tctioyow34emvoti) configuration parameter anyways since ...

**Comment by cicalese** [comment]
> Edit: Still, even with removing just the configuration parameter there is an issue but this is somewhere within the "Semantic Title" extension.

@kghbln What is the remaining SemanticTitle issue? I don't know what the expected behavior is here to tell what might be going wrong.

**Comment by kghbln** [comment]
@cicalese I have been thinking about this again. Actually SemanticTitle is doing what it is supposed to do: Taking the display tiltle and make links to a page with it also use the display title. In case of the SIL extension this is mostly not the desired behaviour since it itself sets an alternate display title for links, i.e. the language names for the content language of the linked page. I think we are cool here. 

Thanks a lot for reacting to this thread.

**Comment by mwjames** [comment]
> since it itself sets an alternate display title for links, i.e. the language names for the content language of the linked page.

Just for clarification:

The mentioned parser function only returns the template content which later is transformed into a link in the manner of `[[{{{target-link}}}|{{{lang-name}}}]]` hence SIL itself doesn't really create any link or alternate title.

It just so happens that the template (and the parameter content produced by SIL) defines a link which then with the help of the parser and additional post-processing (e.g. extensions that hook into the parser processing) creates a title (you could have the template display `{{{target-link}}}` and nothing would happen at all since it wouldn't be a link).

**Comment by kghbln** [comment]
Thanks for adding the clarification. Indeed but if there is a link than it takes what it gets.
