### ISSUE TITLE
Can't install via install.php

### ISSUE THREAD

**Issue by wirehead** [SemanticMediaWiki/SemanticInterlanguageLinks#74]
# Setup and configuration

- SMW version: ~3.0
- SIL version: ~2.0
- MW version: 1.31
- DB (MySQL etc. and version): Sqlite

Given a dockerfile that looks something like this:

```
FROM mediawiki:1.31

ARG COMPOSER_VERSION=1.9.0

# System dependencies

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        zip unzip \
    ; \

    rm -rf /var/lib/apt/lists/*

RUN mkdir /var/www/conf

COPY composer.local.json /var/www/html
COPY conf/LocalSettings.local.php /var/www/conf
COPY conf/LocalSettings.php /var/www/conf

RUN curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
  && curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
  && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }"

RUN php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --version=${COMPOSER_VERSION} \
    && rm -rf /tmp/composer-setup.php \
    && ln -s /var/www/conf/LocalSettings.local.php /var/www/html/LocalSettings.local.php \
    && ln -s /var/www/conf/LocalSettings.php /var/www/html/LocalSettings.php

RUN composer update
```

And a composer.local.json file that looks some thing like this:

```
{
    "require": {
        "mediawiki/semantic-bundle": "~1.0"
    }
}
```

If I log in to this docker container and try to run setup, I type something like this
```
# php maintenance/install.php --dbtype sqlite --dbname "my_wiki" --dbuser "" --dbpassword "" --scriptpath "/var/www/html/" --conf "/var/www/conf/LocalSettings.local.php" user password
```

And I get a result that looks like this:

```
<b>Error:</b> <a href="https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/">Semantic Interlanguage Links</a> requires <a href="https://github.com/SemanticMediaWiki/SemanticMediaWiki/">Semantic MediaWiki</a>. Please enable or install the extension first.
```

I went back and repeated this with a composer.local.json that looked like this:

```
{
    "require": {
		"mediawiki/semantic-media-wiki": "~3.0.0",

		"mediawiki/semantic-result-formats": "~3.0",
		"mediawiki/maps": "~7.4.0",
		"professional-wiki/modern-timeline": "~1.0",
		"mediawiki/mermaid": "~2.1",

		"mediawiki/semantic-extra-special-properties": "~2.0",
		"mediawiki/semantic-compound-queries": "~2.1",

		"mediawiki/semantic-cite": "~2.1",
		"mediawiki/semantic-glossary": "~3.0",
		"mediawiki/semantic-meta-tags": "~2.0",
		"mediawiki/semantic-breadcrumb-links": "~2.0",

		"mediawiki/page-forms": "~4.6"
    }
}
```
(basically, what's in the bundle minus SIL) and it was cooperative.

# Why this is important to me

I'm trying to make a cute SemanticMediaWiki helm chart for Kubernetes that's at least close to a kube-native approach, since the only related Helm chart available is the one that Bitnami provided for regular MediaWiki that uses a lot of Bitnami special sauce and most of the containers out there are more dev-focused than prod-focused.  The easiest way to accomplish setup is to create an init job that runs `install.php` and then `update.php` against the final production container.  If SIL kicks me out with an error message, this means I have to create an intermediate container.

(Also <3 for all of the recent work y'all have done with SMW 3 and getting the SemanticBundle otherwise installable via a Composer module!  Installing other useful MediaWiki bits via tarball downloads makes me a sad panda.)

**Comment by kghbln** [comment]
The current release of the Semantic Bundle provides you with SIL 1.5.0 and consequently a version with autoloading and not with extension registration, i.e. manual loading. I suggest to use

```
{
    "require": {
        "mediawiki/semantic-bundle": "@dev"
    }
}
```
which will give you SIL 2.0.0 and hopefully a fluffy installation process. SIL 2.0.0 was not yet released at the time SB 1.0.0 went public.

@JeroenDeDauw FYI What about SB 1.1.0?
