### ISSUE TITLE
Call to undefined method SearchEngine::defaultNamespaces()

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticInterlanguageLinks#75]
### Setup and configuration

- MediaWiki | 1.34.0-rc.0 (dc7511b)23:35, 16 October 2019
- PHP | 7.2.19-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.41-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (9e30175) 20:07, 17 October 2019
- Semantic Interlanguage Links | 2.1.0-alpha (54a4320) 19:23, 9 September 2019

### Issue

After the upgrade from 1.33.1 of MediaWiki when trying to search via "Special:Search" the following issue occurs.
```
/w/index.php?search=HelloWorld&title=Sp%C3%A9cial%3ARecherche Error from line 47 of /../w/extensions/SemanticInterlanguageLinks/src/Search/SearchResultModifier.php: Call to undefined method SearchEngine::defaultNamespaces()
```

### Backtrace
```
#0 /../w/extensions/SemanticInterlanguageLinks/src/HookRegistry.php(280): SIL\Search\SearchResultModifier->addSearchProfile(array)
#1 /../w/includes/Hooks.php(174): SIL\HookRegistry->SIL\{closure}(array)
#2 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /../w/includes/specials/SpecialSearch.php(717): Hooks::run(string, array)
#4 /../w/includes/specials/SpecialSearch.php(247): SpecialSearch->getSearchProfiles()
#5 /../w/includes/specials/SpecialSearch.php(135): SpecialSearch->load()
#6 /../w/includes/specialpage/SpecialPage.php(575): SpecialSearch->execute(NULL)
#7 /../w/includes/specialpage/SpecialPageFactory.php(611): SpecialPage->run(NULL)
#8 /../w/includes/MediaWiki.php(296): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#9 /../w/includes/MediaWiki.php(900): MediaWiki->performRequest()
#10 /../w/includes/MediaWiki.php(527): MediaWiki->main()
#11 /../w/index.php(44): MediaWiki->run()
#12 {main}
```

**Comment by mwjames** [comment]
> When trying to search via "Special:Search" the following issue occurs.
> ```
> /w/index.php?search=HelloWorld&title=Sp%C3%A9cial%3ARecherche Error from
> line 47 of
> /../w/extensions/SemanticInterlanguageLinks/src/Search/SearchResultModifier.php:
> Call to undefined method SearchEngine::defaultNamespaces()
> ```

This is just great! I'm no so locking forward to coming back, this
extension worked for years and now it is broken because of some WMF
developer removed those methods.

How many extension got broken by MW 1.34? Who is going to fix them?

**Comment by kchenery** [comment]
I have hacked this to get it working on my wiki (just a personal wiki).  All I did was comment out the call to that function in `../w/extensions/SemanticInterlanguageLinks/src/HookRegistry.php`

So the section around line 47 now looks like:
```php
$profiles['sil'] = [
                        'message' => 'sil-search-profile',
                        'tooltip' => 'sil-search-profile-tooltip'/*,
                        'namespaces' => \SearchEngine::defaultNamespaces()*/
                ];
```

Absolutely no idea of the total impact (so not submitting a pull request for it) - but its got my search working again just fine.

**Comment by kghbln** [comment]
@kchenery Thank you for suggesting a hot fix which as far as I can assess only avoids the issue. Still people can move forward instead of de-installing as I did.

**Comment by kghbln** [comment]
@mwjames I would love to get this extension up and running again on sandbox. Also quick and dirty fixes appreciated. :)

**Comment by mwjames** [comment]
> I would love to get this extension up and running again on sandbox. Also quick and dirty fixes appreciated. :)

I don't have SIL currently running on any development system and I cannot easily accommodate to changes while working on SMW. So, if the proposed change fixes the issue for MW 1.34 so be it, give it a ago and see what happens with it on the sandbox otherwise it has to wait for 6+ month.

**Comment by kghbln** [comment]
> So, if the proposed change fixes the issue for MW 1.34 so be it, give it a ago and see what happens with it on the sandbox otherwise it has to wait for 6+ month.

I think this would remove functionality, meaning that we would to the wrong thing for the right reason. I'd rather wait though this extension will be dearly missed on sandbox for sure.

**Comment by kghbln** [comment]
Tested commenting out the line in [SearchResultModifier.php#L47](https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/blob/master/src/Search/SearchResultModifier.php#L47) leads to:

<b>Notice</b>:  Undefined index: namespaces in <b>/.../w/includes/specials/SpecialSearch.php</b> on line <b>252</b><br>
<br>
<b>Notice</b>:  Undefined index: namespaces in <b>/.../w/includes/specials/SpecialSearch.php</b> on line <b>720</b><br>

as well as 

A warning has occurred while searching: Search profile of sil is unrecognized, default search profile will be applied.

**Comment by danielcotton** [comment]
I've been able to get around this by replacing the call to use SearchEngineConfig::defaultNamespaces(), so addSearchProfile now looks like:

```
/**
 * @since 1.0
 *
 * @param array &$profiles
 */
public function addSearchProfile( array &$profiles ) {
         $profiles['sil'] = [
                'message' => 'sil-search-profile',
                'tooltip' => 'sil-search-profile-tooltip',
                'namespaces' => \MediaWiki\MediaWikiServices::getInstance()->getSearchEngineConfig()->defaultNamespaces()
        ];

         return true;
}
```

I'm not familiar with the codebase, so I'm not sure if this is an actual fix or not.

**Comment by danielcotton** [comment]
I've been able to get around this by replacing the call to use SearchEngineConfig::defaultNamespaces(), which is the replacement for the deprecated 'SearchEngine::defaultNamespaces()'. So addSearchProfile now looks like:

```
/**
 * @since 1.0
 *
 * @param array &$profiles
 */
public function addSearchProfile( array &$profiles ) {
         $profiles['sil'] = [
                'message' => 'sil-search-profile',
                'tooltip' => 'sil-search-profile-tooltip',
                'namespaces' => \MediaWiki\MediaWikiServices::getInstance()->getSearchEngineConfig()->defaultNamespaces()
        ];

         return true;
}
```

I'm not familiar with the codebase, so I'm not sure if this is an actual fix or not. If you believe it's suitable, I'm happy to submit a PR.

**Comment by kghbln** [comment]
@mwjames Will this https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/issues/75#issuecomment-584973616 be the fix. It is a dearly missed extension on sandbox. It will be cool to be able to fix it.

**Comment by mwjames** [comment]
> Will this #75 (comment) be the fix? It is a dearly missed extension on sandbox. It will be cool to be able to fix it.

Not really, so I will remove the search functionality from SIL.

**Comment by kghbln** [comment]
> Not really, 

Well, hope dies last.

> so I will remove the search functionality from SIL.

It is always sad to see cool functionality go since content exploration is a key to access data. However I rather see it removed than not using this extension at all.

**Comment by mwjames** [comment]
> It is always sad to see cool functionality go since content exploration is a key to accessing data. However I rather see it removed than not using this extension at all.

You could define a new search form to access the language code in the extended search (`Special:Search`)

**Comment by kghbln** [comment]
> You could define a new search form to access the language code in the extended search (Special:Search)

Right, indeed. Cool. Still need to ingest all the new possibility we have with SMW core. Paradise regained.

**Comment by mwjames** [comment]
> Right, indeed. Cool. Still need to ingest all the new possibility we have with SMW core. Paradise regained.

See [0] but the enabled `Advanced Search` stuff doesn't play nice here so it makes the extended search unusable. 

[0] https://sandbox.semantic-mediawiki.org/w/index.php?title=smw/schema:Simple_search_profile&curid=3186&diff=48511&oldid=12444

**Comment by kghbln** [comment]
Thanks for fixing and providing an example for an alternative. Will kick AdvancedSearch later this day.
