### ISSUE TITLE
Apply language filter on category viewer if language is annotated

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticInterlanguageLinks#9]
Looking at the `by Language` `Special:Search` filtering feature, it is fairly simple to add similar __auto-filtering__ to the `Category` display as soon as a category contains a language declaration using something like `{{INTERLANGUAGELINK:en|Category:Lorem ipsum}}`. 

The added annotation would trigger a filter process for pages within a category and only pages that match the category `languageCode` are being displayed (leaving those pages without/different language code not to be displayed).

A category that does not define a language code is exempted from filtering and will display all pages.

@kghbln Do you have any arguments against auto-filtering if `INTERLANGUAGELINK` is used on category page?

**Comment by kghbln** [comment]
No. I think this will be a nice feature already with smw.o in mind :)
